### База - "климат" (15 записей)

In [5]:
import pandas as pd
import numpy as np
from random import randint, uniform, choice

In [6]:
n = 15 # количество записей
base_data_climate = {
    'код местности': np.random.randint(1, 4, size=n),
    'год наблюдения': np.random.randint(2020, 2026, size=n),
    'абсолютный максимум температуры': np.random.uniform(30, 41, size=n),
    'число дней без осадков': np.random.uniform(80, 141, size=n),
    'средняя температура за год': np.random.uniform(5, 16, size=n)
}

df = pd.DataFrame(base_data_climate)
df

,код местности,год наблюдения,абсолютный максимум температуры,число дней без осадков,средняя температура за год
0,1,2020,35.228977,116.095279,11.964064
1,1,2020,33.841273,87.189601,6.986124
2,1,2025,38.059609,111.020413,13.725467
3,3,2022,31.021996,102.634712,10.030015
4,3,2020,30.659426,100.729435,11.046724
5,3,2024,36.692411,103.264783,11.887689
6,1,2021,38.499701,138.167580,13.792142
7,2,2021,32.005541,108.747496,8.824770
8,3,2022,40.090871,125.187528,11.549129
9,3,2021,37.981521,126.996423,11.165819
10,2,2025,37.704753,90.526600,8.769405
11,3,2022,33.064735,109.554833,9.274918
12,1,2022,37.756998,132.477158,7.196572
13,2,2020,32.320913,139.800529,7.017459
14,2,2020,39.610033,126.943921,5.803902

In [7]:
# 1) напечатать список кодов местностей с числом дней без осадков не менее 100 и средней температурой не более 8 градусов
a = df.loc[
    (df['число дней без осадков'] >= 100) & (df['средняя температура за год'] <= 8),
    'код местности'
]

a

12    1
13    2
14    2
Name: код местности, dtype: int32

In [8]:
# 2) определить код местности с наибольшим абсолютным максимумом температуры
b = df.loc[df['абсолютный максимум температуры'].idxmax(), 'код местности']  # .idxmax() - возвращает индекс строки в которой находится максимальная температура
print(b)

3

### База "Группа" (12 записей)

In [9]:
n = 12
fio = ["Захаров", "Петров", "Смирнов","Сидоров", "Смирнова", "Пупкин", "Иванов", "Чистова", "Цой", "Обаренов", "Ежиков", "Гусев"]
sex = ["муж", "жен", "муж", "муж", "жен", "муж", "муж", "жен", "муж", "муж","муж", "муж"]
base_data_group = {
    'номер по списку': np.arange(1, n+1),
    'Ф.И.О': fio,
    'год рождения': np.random.randint(1960, 2010, size=n),
    'пол': sex,
    'средний балл за сессию': np.random.uniform(2, 5, size=n),
    'наличие пересдач экзаменов': np.random.choice([True, False], size=n)
}

In [10]:
df = pd.DataFrame(base_data_group)
df

,номер по списку,Ф.И.О,год рождения,пол,средний балл за сессию,наличие пересдач экзаменов
0,1,Захаров,1988,муж,3.840845,False
1,2,Петров,2003,жен,4.122027,False
2,3,Смирнов,1997,муж,2.838494,True
3,4,Сидоров,1998,муж,3.594396,False
4,5,Смирнова,2007,жен,2.205332,False
5,6,Пупкин,2008,муж,4.888451,False
6,7,Иванов,1998,муж,3.232464,True
7,8,Чистова,2004,жен,4.346714,False
8,9,Цой,1985,муж,2.166198,False
9,10,Обаренов,1964,муж,3.011592,False
10,11,Ежиков,1967,муж,4.994213,True
11,12,Гусев,1996,муж,4.110426,False

In [11]:
# 1) напечатать список студентов, пересдавших экзамены и имеющих средний балл за сессию не менее 3,5
a = df.loc[(df['наличие пересдач экзаменов'] == True) & (df['средний балл за сессию'] >= 3.5), 'Ф.И.О']
a

10    Ежиков
Name: Ф.И.О, dtype: str

In [12]:
# 2) изменить запись о студенте, 6-м по номеру в списке
df.loc[df['номер по списку'] == 6, 
       ['Ф.И.О', 'год рождения', 'пол', 'средний балл за сессию', 'наличие пересдач экзаменов']] = ['Конев', 2005, 'муж', 4.5, False]

df

,номер по списку,Ф.И.О,год рождения,пол,средний балл за сессию,наличие пересдач экзаменов
0,1,Захаров,1988,муж,3.840845,False
1,2,Петров,2003,жен,4.122027,False
2,3,Смирнов,1997,муж,2.838494,True
3,4,Сидоров,1998,муж,3.594396,False
4,5,Смирнова,2007,жен,2.205332,False
5,6,Конев,2005,муж,4.500000,False
6,7,Иванов,1998,муж,3.232464,True
7,8,Чистова,2004,жен,4.346714,False
8,9,Цой,1985,муж,2.166198,False
9,10,Обаренов,1964,муж,3.011592,False
10,11,Ежиков,1967,муж,4.994213,True
11,12,Гусев,1996,муж,4.110426,False

### База - "команда" (9 записей)

In [17]:
n = 9 
coaches = ["Жуков", "Хомяков", "Старостин", "Минаев", "Минин", "Пожарский", "Соловьев", "Гудини", "Потолков"]
teams = ["Барселона", "Реал", "Медвежонск", "Спартак", "Мадрид", "Звери", "Атлетико", "Питоновские", "The bests"]
data_base_team = {
    "Название команды": teams, 
    "Тренер": coaches, 
    "Место в прошлом сезоне": np.random.randint(1, 10, size=n),
    "Среднее число очков за игру": np.random.randint(30, 120, size=n), 
    "Средний возраст игроков": np.random.uniform(20, 40, size=n)
}

In [18]:
df = pd.DataFrame(data_base_team)
df

,Название команды,Тренер,Место в прошлом сезоне,Среднее число очков за игру,Средний возраст игроков
0,Барселона,Жуков,7,83,26.525232
1,Реал,Хомяков,9,75,38.806328
2,Медвежонск,Старостин,8,44,36.612242
3,Спартак,Минаев,7,59,28.922422
4,Мадрид,Минин,9,64,24.389668
5,Звери,Пожарский,3,34,32.708523
6,Атлетико,Соловьев,5,77,37.536075
7,Питоновские,Гудини,5,99,28.944979
8,The bests,Потолков,7,91,26.268770

In [19]:
# 1) напечатать список тренеров команд, которые набирали за игру в среднем не более 50 очков и заняли место не выше 5-го
a = df.loc[(df['Среднее число очков за игру'] <= 50) & (df['Место в прошлом сезоне'] >= 5), 'Тренер']
a

2    Старостин
Name: Тренер, dtype: str

In [20]:
# 2) Упорядочить записи в базе в алфавитном порядке по фамилии тренера
df = df.sort_values(by='Тренер', ignore_index=True)
df

,Название команды,Тренер,Место в прошлом сезоне,Среднее число очков за игру,Средний возраст игроков
0,Питоновские,Гудини,5,99,28.944979
1,Барселона,Жуков,7,83,26.525232
2,Спартак,Минаев,7,59,28.922422
3,Мадрид,Минин,9,64,24.389668
4,Звери,Пожарский,3,34,32.708523
5,The bests,Потолков,7,91,26.268770
6,Атлетико,Соловьев,5,77,37.536075
7,Медвежонск,Старостин,8,44,36.612242
8,Реал,Хомяков,9,75,38.806328

### База - "UFO" (14 записей)

In [28]:
n = 14
data_base_ufo = {
    "Тип (код) UFO": np.random.randint(1, 4, size=n),
    "продолжительность наблюдения в часах": np.random.uniform(0.01, 2, size=n),
    "дата появления (день, месяц, год)": pd.to_datetime('2022-06-14') + pd.to_timedelta(
        np.random.randint(0, 366, size=n), unit="D"
    ),
    "время появления в часах": np.random.randint(0, 24, size=n),
    "Наличие световых эффектов (да, нет)": np.random.choice([True, False], size=n),
    "Наличие звуковых эффектов(да, нет)": np.random.choice([True, False], size=n)
}

In [29]:
df = pd.DataFrame(data_base_ufo)
df

,Тип (код) UFO,продолжительность наблюдения в часах,"дата появления (день, месяц, год)",время появления в часах,"Наличие световых эффектов (да, нет)","Наличие звуковых эффектов(да, нет)"
0,3,0.683303,2023-05-24,12,True,True
1,2,0.462882,2022-11-14,11,False,False
2,3,0.067648,2022-11-20,1,True,True
3,1,0.824231,2023-01-08,4,False,True
4,3,1.847170,2023-05-16,17,False,False
5,2,0.290468,2022-12-27,23,False,True
6,3,1.665317,2022-08-10,21,False,True
7,3,0.539972,2023-06-11,12,False,False
8,2,1.984045,2023-03-18,11,True,True
9,1,1.956101,2023-03-29,6,False,False
10,2,1.009190,2023-04-11,0,True,False
11,2,0.955928,2022-08-06,9,True,False
12,2,0.115721,2023-02-15,19,True,False
13,2,0.919573,2023-05-14,2,True,True

In [31]:
# 1) напечатать список типов UFO, которые наблюдались не менее 0,1 часа и сопровождались световыми и звуковыми эффектами
a = df.loc[(df['время появления в часах'] >= 0.1) & (df['Наличие световых эффектов (да, нет)'] == True) & (df['Наличие звуковых эффектов(да, нет)'] == True), 'Тип (код) UFO']
a

0     3
2     3
8     2
13    2
Name: Тип (код) UFO, dtype: int32

In [35]:
# 2) Упорядочить записи в базе по значению даты появления в порядке возрастания года, месяца, числа.
df = df.sort_values('дата появления (день, месяц, год)', ignore_index=True)
df

,Тип (код) UFO,продолжительность наблюдения в часах,"дата появления (день, месяц, год)",время появления в часах,"Наличие световых эффектов (да, нет)","Наличие звуковых эффектов(да, нет)"
0,2,0.955928,2022-08-06,9,True,False
1,3,1.665317,2022-08-10,21,False,True
2,2,0.462882,2022-11-14,11,False,False
3,3,0.067648,2022-11-20,1,True,True
4,2,0.290468,2022-12-27,23,False,True
5,1,0.824231,2023-01-08,4,False,True
6,2,0.115721,2023-02-15,19,True,False
7,2,1.984045,2023-03-18,11,True,True
8,1,1.956101,2023-03-29,6,False,False
9,2,1.009190,2023-04-11,0,True,False
10,2,0.919573,2023-05-14,2,True,True
11,3,1.847170,2023-05-16,17,False,False
12,3,0.683303,2023-05-24,12,True,True
13,3,0.539972,2023-06-11,12,False,False